nome : principal

em : [empurrar]

empregos :
  teste :
    roda em : ubuntu-mais recente

    passos :
      - usa : ações / checkout @ v2
      - usa : ações / nó de configuração @ v2
        com :
          cache : yarn
          versão do nó : 16
      - run : yarn install --frozen-lockfile

      - correr : tipo de fio
      - correr : fio de fiapo
      - executar : teste de fio --ci

  benchmark de teste :
    roda em : ubuntu-mais recente

    passos :
      - usa : ações / checkout @ v2
      - usa : ações / nó de configuração @ v2
        com :
          cache : yarn
          versão do nó : 16
      - run : yarn install --frozen-lockfile

      - executar : (pacotes de cd / criador de gif; benchmark yarn)

  ação-teste :
    roda em : ubuntu-mais recente
    necessidades : build-docker-image

    passos :
      - nome : gerar-jogo-cobra-de-grade-contribuição-do-github
        id : snake-gif
        usa : Platane / snk @ master
        com :
          github_user_name : platane
          gif_out_path : dist / github-Contribution-grid-snake.gif
          svg_out_path : dist / github-Contribution-grid-snake.svg

      - nome : certifique-se de que o arquivo gerado existe
        correr : |
          ls -l $ {{steps.snake-gif.outputs.gif_out_path}}
          test -f $ {{steps.snake-gif.outputs.gif_out_path}}
      - usa : crazy-max/ghaction-github-pages@v2.5.0
        com :
          target_branch : output
          build_dir : dist
        env :
          GITHUB_TOKEN : $ {{secrets.MY_GITHUB_TOKEN_GH_PAGES}}

  deploy-ghpages :
    roda em : ubuntu-mais recente
    passos :
      - usa : ações / checkout @ v2
      - usa : ações / nó de configuração @ v2
        com :
          cache : yarn
          versão do nó : 16
      - run : yarn install --frozen-lockfile

      - run : yarn build: demo
        env :
          GITHUB_USER_CONTRIBUTION_API_ENDPOINT : https://snk-one.vercel.app/api/github-user-contribution/

      - usa : crazy-max/ghaction-github-pages@v2.5.0
        if : success () && github.ref == 'refs / heads / master'
        com :
          target_branch : gh-pages
          build_dir : packages / demo / dist
        env :
          GITHUB_TOKEN : $ {{secrets.MY_GITHUB_TOKEN_GH_PAGES}}

  build-docker-image :
    roda em : ubuntu-mais recente
    passos :
      - usa : ações / checkout @ v2
      - usa : ações / nó de configuração @ v2
        com :
          cache : yarn
          versão do nó : 16
      - run : yarn install --frozen-lockfile

      - run : yarn build: action

      - usa : docker / setup-qemu-action @ v1

      - usa : docker / setup-buildx-action @ v1

      - usa : docker / login-action @ v1
        com :
          nome de usuário :ericasrafael
      - usa : docker / build-push-action @ v2
        id : docker_build
        com :
          push : $ {{github.ref == 'refs / heads / master'}}
          tags : |
            platane / snk: mais recente
            platane / snk: $ {{github.sha}}
          arquivo : packages / action / Dockerfile
          contexto : pacotes / ação
